# Path to the nray example `loader_3d` binary.
loader_3d=./loader_3d

all:
	${loader_3d} cube.scene
	mv out.png ../../../img/cuboid3d.png
	${loader_3d} cone.scene
	mv out.png ../../../img/cone3d.png
	${loader_3d} cylinder.scene
	mv out.png ../../../img/cylinder3d.png
	${loader_3d} capsule.scene
	mv out.png ../../../img/capsule3d.png
	${loader_3d} msum.scene
	mv out.png ../../../img/msum3d.png
	${loader_3d} cso.scene
	mv out.png ../../../img/cso3d.png
	${loader_3d} refl.scene
	mv out.png ../../../img/refl3d.png
	${loader_3d} compound.scene
	mv out.png ../../../img/compound3d.png
	${loader_3d} mesh.scene
	mv out.png ../../../img/mesh3d.png
	${loader_3d} ball.scene
	mv out.png ../../../img/ball3d.png
	${loader_3d} convex.scene
	mv out.png ../../../img/convex3d.png
