use std::any::Any;

use utils::IdAllocator;
use geometry::shape::Shape;
use geometry::query::{ContactManifold, ContactPrediction};
use math::Point;

/// Trait implemented algorithms that compute contact points, normals and penetration depths.
pub trait ContactManifoldGenerator<N: Real, M>: Any + Send + Sync {
    /// Runs the collision detection on two objects. It is assumed that the same
    /// collision detector (the same structure) is always used with the same
    /// pair of object.
    fn update(
        &mut self,
        dispatcher: &ContactDispatcher<P, M>,
        ida: usize,
        ma: &Isometry<N>,
        a: &Shape<N>,
        idb: usize,
        mb: &Isometry<N>,
        b: &Shape<N>,
        prediction: &ContactPrediction<N>,
        id_alloc: &mut IdAllocator,
    ) -> bool;

    /// The number of contacts found.
    fn num_contacts(&self) -> usize;

    /// Collects the contact manifolds generated by the last update.
    fn contacts<'a: 'b, 'b>(&'a self, out: &'b mut Vec<&'a ContactManifold<P>>);
}

pub type ContactAlgorithm<P, M> = Box<ContactManifoldGenerator<P, M>>;

pub trait ContactDispatcher<P, M>: Any + Send + Sync {
    /// Allocate a collision algorithm corresponding to the given pair of shapes.
    fn get_contact_algorithm(
        &self,
        a: &Shape<N>,
        b: &Shape<N>,
    ) -> Option<ContactAlgorithm<P, M>>;
}
